
insert into "School"("schoolCode","schoolName","schoolShortName")
values
    ('QHL','Trường Đại học Luật (ĐHQG Hà Nội)','NA'),
    ('QHQ','Trường Quốc tế (ĐHQG Hà Nội)','NA'),
    ('QHY','Trường ĐẠI HỌC Y Dược (ĐHQG Hà Nội)','NA'),
    ('QHI','Trường ĐẠI HỌC Công nghệ (ĐHQG Hà Nội)','NA'),
    ('QHE','Trường ĐẠI HỌC Kinh tế (ĐHQG Hà Nội)','NA'),
    ('QHS','Trường Đại học Giáo dục (ĐHQG Hà Nội)','NA'),
    ('QHT','Trường Đại học Khoa học Tự nhiên (ĐHQG Hà Nội)','NA'),
    ('QHX','Trường ĐH Khoa học Xã hội và Nhân văn (ĐHQG Hà Nội)','NA'),
    ('QHD','Trường Quản trị và kinh doanh (ĐHQG Hà Nội)','NA'),
    ('QHF','Trường ĐẠI HỌC Ngoại ngữ (ĐHQG Hà Nội)','NA'),
    ('VJU','Trường ĐẠI HỌC Việt Nhật (ĐHQG Hà Nội)','NA'),
    ('NVH','HỌC VIỆN Âm nhạc Quốc gia Việt Nam','NA'),
    ('HBT','HỌC VIỆN Báo chí Tuyên truyền','NA'),
    ('HCP','HỌC VIỆN Chính sách và Phát triển','NA'),
    ('BVH','HỌC VIỆN Công nghệ Bưu chính Viễn thông','NA'),
    ('HCH','HỌC VIỆN Hành chính Quốc gia','NA'),
    ('KMA','HỌC VIỆN Kỹ thuật Mật mã','NA'),
    ('NHH','HỌC VIỆN Ngân hàng','NA'),
    ('HQT','HỌC VIỆN Ngoại giao','NA'),
    ('HVN','HỌC VIỆN Nông nghiệp Việt Nam','NA'),
    ('HPN','HỌC VIỆN Phụ nữ Việt Nam','NA'),
    ('HVQ','HỌC VIỆN Quản lý Giáo dục','NA'),
    ('HTC','HỌC VIỆN Tài chính','NA'),
    ('HTN','HỌC VIỆN Thanh Thiếu niên Việt Nam','NA'),
    ('HTA','HỌC VIỆN Tòa án','NA'),
    ('HYD','HỌC VIỆN Y Dược học cổ truyền Việt Nam','NA'),
    ('BKA','ĐẠI HỌC Bách khoa Hà Nội','NA'),
    ('LDA','Trường ĐẠI HỌC Công đoàn','NA'),
    ('GTA','Trường ĐẠI HỌC Công nghệ Giao thông vận tải','NA'),
    ('CCM','Trường ĐẠI HỌC Công nghiệp Dệt may Hà Nội','NA'),
    ('DCN','Trường ĐẠI HỌC Công nghiệp Hà Nội','NA'),
    ('VHD','Trường ĐẠI HỌC Công nghiệp Việt Hung','NA'),
    ('DDN','Trường ĐẠI HỌC Đại Nam','NA'),
    ('DDL','Trường ĐẠI HỌC Điện lực','NA'),
    ('DKH','Trường ĐẠI HỌC Dược Hà Nội','NA'),
    ('FPT','Trường ĐẠI HỌC FPT','NA'),
    ('GHA','Trường ĐẠI HỌC Giao thông vận tải','NA'),
    ('NHF','Trường ĐẠI HỌC Hà Nội','NA'),
    ('ETU','Trường ĐẠI HỌC Hòa Bình','NA'),
    ('KCN','Trường ĐẠI HỌC Khoa học và Công nghệ Hà Nội','NA'),
    ('DKS','Trường ĐẠI HỌC Kiểm sát Hà Nội','NA'),
    ('KTA','Trường ĐẠI HỌC Kiến trúc Hà Nội','NA'),
    ('DKK','Trường ĐẠI HỌC Kinh tế Kỹ thuật Công nghiệp','NA'),
    ('KHA','Trường ĐẠI HỌC Kinh tế Quốc dân','NA'),
    ('LNH','Trường ĐẠI HỌC Lâm nghiệp','NA'),
    ('DLX','Trường ĐẠI HỌC Lao động Xã hội','NA'),
    ('LPH','Trường ĐẠI HỌC Luật Hà Nội','NA'),
    ('MDA','Trường ĐẠI HỌC Mỏ Địa chất Hà Nội','NA'),
    ('MTC','Trường ĐẠI HỌC Mỹ thuật Công nghiệp','NA'),
    ('MTH','Trường ĐẠI HỌC Mỹ thuật Việt Nam','NA'),
    ('NTH','Trường ĐẠI HỌC Ngoại thương','NA'),
    ('NTU','Trường ĐẠI HỌC Nguyễn Trãi','NA'),
    ('SKD','Trường ĐẠI HỌC Sân khấu Điện ảnh','NA'),
    ('SPH','Trường ĐẠI HỌC Sư phạm Hà Nội','NA'),
    ('GNT','Trường ĐẠI HỌC Sư phạm Nghệ thuật Trung ương Hà Nội','NA'),
    ('TDH','Trường ĐẠI HỌC Sư phạm Thể dục thể thao Hà nội','NA'),
    ('FBU','Trường ĐẠI HỌC Tài chính Ngân hàng Hà Nội','NA'),
    ('DMT','Trường ĐẠI HỌC Tài nguyên và Môi trường Hà Nội','NA'),
    ('DTL','Trường ĐẠI HỌC Thăng Long','NA'),
    ('TDD','Trường ĐẠI HỌC Thành Đô','NA'),
    ('HNM','Trường ĐẠI HỌC Thủ đô Hà Nội','NA'),
    ('TMU','Trường ĐẠI HỌC Thương mại','NA'),
    ('TLA','Trường ĐẠI HỌC Thủy lợi','NA'),
    ('VHH','Trường ĐẠI HỌC Văn hóa Hà Nội','NA'),
    ('XDA','Trường ĐẠI HỌC Xây dựng Hà Nội','NA'),
    ('YHB','Trường ĐẠI HỌC Y Hà Nội','NA'),
    ('YTC','Trường ĐẠI HỌC Y tế Công cộng','NA'),
    ('DCQ','Trường ĐẠI HỌC Công nghệ và Quản lý Hữu nghị','NA'),
    ('DDU','Trường ĐẠI HỌC Đông Đô','NA'),
    ('DQK','Trường ĐẠI HỌC Kinh doanh và Công nghệ Hà Nội','NA'),
    ('DPD','Trường ĐẠI HỌC Phương Đông','NA'),
    ('MHN','Trường ĐẠI HỌC Mở Hà Nội','NA'),
    ('PKA','Trường ĐẠI HỌC Phenikaa','NA'),
    ('CMC','Trường ĐẠI HỌC CMC','NA')
